name: Common

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  commitlint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v6
